<?php
helper('auth');
$db=db();
$where=[
    'id[>]'=>0,
    'ORDER'=>[
        'created_at'=>'DESC'
    ]
];
$mensagens=$db->select('mensagens','*',$where);
$user=isAuth();
$data=[
    'mensagens'=>$mensagens,
    'user'=>$user
];
if($user){
    view("homeOnline",$data);
}else{
    view("homeOffline",$data);
}
?>
