<?php
helper('auth');
$db=db();
$where=[
    'id[>]'=>0,
    'ORDER'=>[
        'created_at'=>'DESC'
    ]
];
$mensagensArr=$db->select('mensagens','*',$where);
$mensagens=null;
foreach ($mensagensArr as $key => $mensagem) {
    $mensagens[$key]=$mensagem;
    $mensagens[$key]['name']=getUserById($mensagem['user_id'])['name'];
}
$user=isAuth();
$data=[
    'mensagens'=>$mensagens,
    'user'=>$user
];
if($user){
    view("homeOnline",$data);
}else{
    view("homeOffline",$data);
}
?>
