<?php
helper('auth');
$db=db();
$name=@$_POST['name'];
$msg=@$_POST['msg'];
$where=[
    'id'=>segment(2)
];
$crud=segment(3);
if(isAuth()){
    if($crud=='apagar'){
        $db->delete("mensagens",$where);
        $url='/';
        redirect($url);
    }elseif(strlen($name)<1){
        $data=[
            'title'=>'Erro',
            'msg'=>'Digite o seu nome'
        ];
        view('erro',$data);
    }elseif(strlen($msg)<1){
        $data=[
            'title'=>'Erro',
            'msg'=>'Digite uma mensagem'
        ];
        view('erro',$data);
    }else{
        if($crud=='editar'){
            $data=[
                'name'=>$name,
                'msg'=>$msg,
                'updated_at'=>time()
            ];
            $db->update("mensagens",$data,$where);
        }else{
            $data=[
                'name'=>$name,
                'msg'=>$msg,
                'created_at'=>time()
            ];
            $db->insert("mensagens",$data);
        }
        redirect('/');
    }
}else{
    redirect('/signin');
}
