<?php
$name=@$_POST['name'];
$msg=@$_POST['msg'];
$where=[
    'id'=>segment(2)
];
$crud=segment(3);
if(strlen($name)<1){
    $data=[
        'title'=>'Erro',
        'msg'=>'Digite o seu nome'
    ];
    view('erro',$data);
}elseif(strlen($msg)<1){
    $data=[
        'title'=>'Erro',
        'msg'=>'Digite uma mensagem'
    ];
    view('erro',$data);
}else{
    $data=[
        'name'=>$name,
        'msg'=>$msg,
        'created_at'=>time()
    ];
    $db=db();
    if($crud=='editar'){
        $db->update("mensagens",$data,$where);
    }elseif($crud=='apagar'){
        $db->delete("mensagens",$where);
    }else{
        $db->insert("mensagens",$data);
    }
    $url='/';
    redirect($url);
}
?>
