<?php
helper("auth");
$user=signin();
if(isset($user['error'])){
    $data=[
        'error'=>$user['error'],
        'title'=>'Entrar'
    ];
    view('signin',$data);
}else{
    if($user['type']=='admin'){
        redirect('/user');
    }else{
        redirect('/');
    }
}
